artifacts_root: artifacts #it will store artifacts for every new experiment

data ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/Maulik-Manipal/Test2/raw/refs/heads/main/samsumdata.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion